#ifndef ASSERV_PETIT_ROBOT_PID_COEFS_H
#define ASSERV_PETIT_ROBOT_PID_COEFS_H


#define MOTOR_SPEED_P 20
#define MOTOR_SPEED_I 20
#define MOTOR_SPEED_D 0

#define MOTOR_POS_P 0.01
#define MOTOR_POS_I 0
#define MOTOR_POS_D 0


#endif //ASSERV_PETIT_ROBOT_PID_COEFS_H
